name: Build Linux WHL
on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true  # 强制启用 Node.js 24，消除所有警告
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Build wheel
        run: |
          pip install -U pip build wheel
          tar zxf *.tar.gz
          cd $(ls -d */ | head -n1)
          python -m build --wheel

      - uses: actions/upload-artifact@v4
        with:
          name: linux-whl
          path: "*/dist/*.whl"
