name: Build Linux WHL
on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2  # 已支持 Node.js 24

      - name: Set up Python
        uses: actions/setup-python@v5.3.0  # 已支持 Node.js 24
        with:
          python-version: "3.10"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip build wheel setuptools

      - name: Build wheel for Linux
        run: |
          tar zxf *.tar.gz
          cd $(ls -d */ | head -n1)
          python -m build --wheel

      - name: Upload wheel
        uses: actions/upload-artifact@v4.4.0  # 已支持 Node.js 24
        with:
          name: linux-whl
          path: "*/dist/*.whl"
